### ISSUE TITLE
I get this error lol

### ISSUE THREAD

**Issue by adarshxs** [0hq/WebGPT#16]
Access to fetch at 'file:///C:/Users/idgaf/OneDrive/Desktop/WebGPT/models/better_shakespeare/params_gpt.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.

Cuz we are loading the model using either file:// or C:/, which stays true to the error message as they are not http://

I'll PR a fix in the readme

**Comment by 0hq** [comment]
Ah got it, I should make this clearer.

**Comment by adarshxs** [comment]
Ya just spin up a local server in the working dir
