### ISSUE TITLE
what different with mlc-ai/web-llm

### ISSUE THREAD

**Issue by jingslunt** [0hq/WebGPT#21]
https://github.com/mlc-ai/web-llm

**Comment by 0hq** [comment]
Sure. 

WebLLM is using TVM and compiling from C++ to WebAssembly, which is more performant but vastly more complicated. This is built to be both a solid educational reference as well as a place to start more complex projects from, being only written in a small amount of Javascript. 

Considering using Javascript here has minor performance impacts vs. the simplicity it provides (mostly all computation is done on WebGPU, meaning Javascript isn't involved), this is preferable in various circumstances.

**Comment by jingslunt** [comment]
> Sure.
> 
> WebLLM is using TVM and compiling from C++ to WebAssembly, which is more performant but vastly more complicated. This is built to be both a solid educational reference as well as a place to start more complex projects from, being only written in a small amount of Javascript.
> 
> Considering using Javascript here has minor performance impacts vs. the simplicity it provides (mostly all computation is done on WebGPU, meaning Javascript isn't involved), this is preferable in various circumstances.

the same as this proj?  https://xenova.github.io/transformers.js

**Comment by cnrpman** [comment]
@jingslunt It's using onnxruntimeweb, mature but no webGPU backend for now.

**Comment by jingslunt** [comment]
> @jingslunt It's using onnxruntimeweb, mature but no webGPU backend for now.
webgpu merged
https://github.com/microsoft/onnxruntime/pull/14579
