### ISSUE TITLE
kmeans.org unsupported browser message

### ISSUE THREAD

**Issue by Y-Kelly** [0hq/WebGPT#24]
Hi!  Reaching out from the Microsoft Edge team! 

When visiting kmeans.org with a browser that does not have WebGPU support the site recommends using Chrome.  

![image](https://user-images.githubusercontent.com/74324031/234663731-05189af5-9d63-4ef0-902a-78605dcdc9a9.png)

Is it possible to update the message to include Edge Canary (https://www.microsoftedgeinsider.com/en-us/download/canary)?  I already see that when visiting the site in Edge Canary the message says that “WebGPU is supported in your browser!”

**Comment by jumaHarun** [comment]
This would make such an awesome first PR. Can I get assigned to this?

**Comment by 0hq** [comment]
Updated to include Edge Canary!

**Comment by Y-Kelly** [comment]
Thank you :)

**Comment by Y-Kelly** [comment]
@0hq Our team reviewed the update and asked if there could be a slight modification.  

Would it be able to say the following?  

"WebGPU is not supported in your browser yet. Update Chrome or Edge to v113 or download [Chrome Canary](https://www.google.com/chrome/canary/) or [Edge Canary](https://www.microsoftedgeinsider.com/en-us/download/canary)."

Thank you!!!
