### ISSUE TITLE
SyntaxError: Unexpected token 'v', "version ht"... is not valid JSON

### ISSUE THREAD

**Issue by doroved** [0hq/WebGPT#25]
1. Cloned a repository
2. I ran it through Live Server
3. I installed **brew install git-lfs**
4. I clicked Load GPT2 Model

I get an error like this. What seems to be the problem?

<img width="624" alt="image" src="https://user-images.githubusercontent.com/30116541/234743791-fc21ed12-28bd-4f2a-8e98-0f2818ee60b1.png">

**Comment by doroved** [comment]
That's it, it worked. I should have run **git lfs install** in the project folder and after **git lfs pull**

**Comment by abhishekmeena33** [comment]
Please can you tell me how should I solve this problem, I have done **git lfs install** and **git lfs pull**, but it doesn't seem to work out. I am working with model viewer API from google.
![image](https://github.com/0hq/WebGPT/assets/118628637/14381eed-7098-412b-9847-1b9ea004a4d7)
