### ISSUE TITLE
Error on MacOS

### ISSUE THREAD

**Issue by rpruizc** [0hq/WebGPT#7]
After cloning the repo and enabling WebGPU in my canary chrome 114, when I tried to load either of the models, I get a console error:

```
Loading model from folder: gpt2

VM16:1 Uncaught (in promise) SyntaxError: Unexpected token 'v', "version ht"... is not valid JSON

await (async)
onclick @ (index):18`
```

This, when run in an M1 MacOS 13.3 MacBook pro

Any ideas? Thanks!

**Comment by felladrin** [comment]
You need to install Git LFS (`brew install git-lfs`) and then run `git lfs install && git lfs pull` in the folder where you cloned this repository. This will start the download of the files from `models` folder.

After it finishes downloading them, it should work fine through a local server:
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/418083/233645262-7099bca6-d70d-4415-baf5-3a93d54e1528.png">

**Comment by rpruizc** [comment]
Thank you! That solved it.
