### ISSUE TITLE
Does "Unsafe WebGPU" flag still need to be set to "enabled"?

### ISSUE THREAD

**Issue by felladrin** [0hq/WebGPT#8]
Hi! 👋 Thanks for sharing your project!

I've got a question about this part of the Readme:

https://github.com/0hq/WebGPT/blob/5ce0182a81a049784173be1ae19d4742d79a1768/README.md?plain=1#L15

On Chrome Canary v114, I couldn't see the difference between running it with the flag enabled and disabled.
Could you clarify why it's recommended to enable this flag?

**Comment by 0hq** [comment]
Good point, I'll investigate more deeply. This was recommended in documentation but this might only be for vanilla Chrome pre-v113.

**Comment by 0hq** [comment]
Isn't needed anymore + registered for the Chrome Origin Trial.
